------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">1.- ✍ Introducción.</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [86]:
# importar numpy con alias np
import numpy as np

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">2.- ✍ Funciones matemáticas y constantes</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [87]:
np.pi

3.141592653589793

In [88]:
np.e

2.718281828459045

In [89]:
np.log(10)

2.302585092994046

In [90]:
# coeficiente de correlación de Pearson
x = np.array([
    [1, 2, 3, 4, 5, 6, 8, 12, 11, 19],
    [7, 8, 9, 10, 11, 12, 13 ,14 ,15 ,16]
])
np.corrcoef(x)

array([[1.       , 0.9361986],
       [0.9361986, 1.       ]])

In [91]:
# media aritmética
np.mean(x)

9.3

In [92]:
# suma acumulada de los valores del array
np.cumsum(x)

array([  1,   3,   6,  10,  15,  21,  29,  41,  52,  71,  78,  86,  95,
       105, 116, 128, 141, 155, 170, 186], dtype=int32)

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">3.- ✍ Generación de array-s y alguna operación matemática</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [93]:
# Generar array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [94]:
# Tipo de dato
a = np.array([1, 2, 3.0, 7.67])
print(a.dtype)

float64


In [95]:
# Generar array de tipo flotante
np.array([1, 2, 3, 9, 13], dtype=float)

array([ 1.,  2.,  3.,  9., 13.])

In [96]:
# De tipo complejo
np.array([1, 2, 3, 4 , 5], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [97]:
a

array([1.  , 2.  , 3.  , 7.67])

In [98]:
# conversión a tipo entero
a.astype(int)

array([1, 2, 3, 7])

In [99]:
# un nuevo array de forma y tipo dados, sin inicializar las entradas.
s = np.empty((3,3))
print (s)
s.shape

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


(3, 3)

In [100]:
X, Y = 5, 5
print (np.empty(25))
# matriz de 5x5 sin inicializar valores
j = np.empty(25).reshape(X, Y)
# matrices de 5x5 con valores aleatorios
k = np.random.rand(25).reshape(X, Y)
l = np.random.rand(25).reshape(X, Y)

[1.7454481  0.43356849 1.70835803 0.04599062 1.62229028 0.02432716
 0.71290482 0.26273636 0.06693171 1.80025274 0.04135889 0.21219824
 1.03793536 0.23163191 0.82717439 1.43819999 0.27251404 0.0153828
 1.0402899  1.51134414 0.00489321 0.57744352 0.01927083 0.167236
 0.00915435]


In [101]:
# Suma de dos arrays
j = j + l
print (j)
# Multiplicación de dos arrays
j = j * l
print (j)

[[1.95830794 0.46826346 2.04774387 0.44259477 2.03240453]
 [0.43968405 1.42289871 0.6070586  0.14161547 1.9744201 ]
 [0.43019168 0.67654292 1.84388711 0.25817586 0.8886237 ]
 [2.42169878 1.08439166 0.8811285  1.80419498 2.24069764]
 [0.99671016 0.92879433 0.52720125 0.80725418 0.52647179]]
[[0.4168451  0.01624638 0.69497528 0.17553492 0.83351807]
 [0.1826258  1.01024937 0.20902377 0.01057638 0.34387954]
 [0.16727263 0.31414911 1.48608404 0.00685301 0.05460531]
 [2.3817378  0.88039333 0.7628332  1.3782337  1.63426067]
 [0.98855404 0.32633264 0.26778155 0.51665735 0.27235304]]


------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">4.- ✍ Indexación de Array-s y búsqueda de elementos</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [102]:
# generar array
z = np.array([
    [1, 2, 3, 4, 5, 6, 8, 12, 11, 19],
    [7, 8, 9, 10, 11, 12, 13 ,14 ,15 ,16]
])
print (z.shape)

(2, 10)


In [103]:
# segunda fila
z[1]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [104]:
# corte entre segunda fila y segunda columna
z[1, 1]

8

In [105]:
# de la primera fila el corte con las columnas desde la 0 hasta la 2
z[0, 0:3]

array([1, 2, 3])

In [106]:
# corte de la primera fila con las columnas desde la primera hasta la última dando saltos de tres en tres
z[0, ::3]

array([ 1,  4,  8, 19])

In [107]:
# penúltima posición de la segunda fila
z[1, -2]

15

------------------------------------------------------------------------------------------------------<br>
<h2 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">5. Generar array-s</h2>

* A partir de array-s generados: `array`, `copy`
* 1 y 0: `empty`, `eye`, `ones`, `zeros`, `*_like`
* Rangos: `arange`, `linspace`, `logspace`, `meshgrid`
* Aleatorios: `rand`, `randn`

------------------------------------------------------------------------------------------------------<br>



In [108]:
# matriz identidad de 3x3
np.identity(3).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [109]:
# saber diemensión de la matriz de la celda anterior
_.shape

(3, 3)

In [110]:
# matriz de unos
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [111]:
# matriz de ceros
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [112]:
# matriz identidad de 2x2
identidad = np.identity(2)
identidad

array([[1., 0.],
       [0., 1.]])

In [113]:
identidad.shape

(2, 2)

In [114]:
# matriz de unos con la dimensión de la matriz identidad
np.ones(identidad.shape)

array([[1., 1.],
       [1., 1.]])

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">6.- ✍ Rangos.</h3><br>

* linspace(start, stop, num=50)
* meshgrid 

------------------------------------------------------------------------------------------------------<br>


In [115]:
# vector del 0 al 10 separarado proporcionalmente en 5 rangos. Parecido al meshgrid
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">7.- ✍ Más operaciones con Array-s.</h3><br>

* Funciones matemáticas: `sin`, `cos`, `sqrt`, `exp`, ...
* Operadores lógicos: `<`, `~`, ...
* Funciones lógicas: `all`, `any`, `isnan`, `allclose`, ...

------------------------------------------------------------------------------------------------------<br>


In [116]:
# array del 0 al 8 de uno en uno
a = np.arange(3*3)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [117]:
# del 3 al 6 de uno en uno en coma flotante
a = np.arange(3., 7.)
a

array([3., 4., 5., 6.])

In [118]:
# array del 0 al 6 de uno en uno y dimensión de 2x3
a = np.arange(2 * 3).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [119]:
# raíz cuadrada de una matriz
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [120]:
# números complejos
np.arange(-3, 3).astype(complex)

array([-3.+0.j, -2.+0.j, -1.+0.j,  0.+0.j,  1.+0.j,  2.+0.j])

In [121]:
# generación de 2 vectores
a = np.arange(-1, 8)
b = np.zeros(9).astype(int)
a, b

(array([-1,  0,  1,  2,  3,  4,  5,  6,  7]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [122]:
# comparación booleana
a < b

array([ True, False, False, False, False, False, False, False, False])

In [123]:
# si se cumple la condición en alguna de las posiciones es True
np.any(a < b)

True

In [124]:
# si se cumple la condición en todas las posiciones es True
np.all(a < b)

False

<h3>👏👏👏 You guys rock !!!</h3>